image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -f src/main/docker/Dockerfile -t wenet/profile-manager .
