image: docker:latest

variables:
  DOCKER_HOST: tcp://docker:2375

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -f src/main/docker/Dockerfile -t wenet/profile-manager .
