image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -f src/main/docker/Dockerfile -t wenet/profile-manager .
