image: atlassian/default-image:2

pipelines:
  tags:
    '*':
        - step:
            name: 'Build docker image for tags'
            script:
                - ./buildDockerImage.sh
                - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
                - docker push internetofus/profile-manager:$BITBUCKET_TAG
            services:
                - docker
  branches:
    'master':
        - step:
            name: 'Build docker image for production'
            script:
                - ./buildDockerImage.sh
                - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
                - docker push internetofus/profile-manager:latest
            services:
                - docker
