resourcePackages:
- eu.internetofus.wenet_profile_manager.api
prettyPrint: true
cacheTTL: 0
openAPI:
  tags:
    - name: Other
      description: Other services provided by the API.
    - name: Intelligences
      description: Provide the functionality to evaluate the intelligences of a person
    - name: Personalities
      description: Provide the functionality to evaluate the personality of a person
    - name: Historic
      description: The functionality provided allows to access to the values of the models in a previous dates.
    - name: Profiles
      description: The functionality provided allows to access current and previous values of user attributes that define the user profile.  It also allows you to modify the current values.
    - name: Trusts
      description: The functionality provided allows to manage the trust over other users.
  info:
    # The verion of the API has to be synchonized with the 'api-version' property of the 'pom.xml'
    version: '0.11.0'
    title: WeNet - Profile manager API
    description:  >-
      The profile manager component is the one responsible for storing and maintaining the WeNet user profiles
      and its historic. An user profile is a set of attributes that define the state of the user. Some of these
      attributes are filled in by the user, such as name, email, telephone,..., or by  other components of
      the platform, such as social relationships, routines,.... Every time a profile is modified a copy of
      the previous profile values is stored in the historic. This allows to know, to the rest of components,
      how the state of the user evolves in the time.


      Another responsibility of the profile manager is to evaluate the trust of one user over another when it is
      doing some action. The trust is dynamic and will be updated every time they collaborate to achieve a task.
      When a user has received help it can rate the performance of the user that has helped it. For this it has to
      post a performance rating event to the profile manager. These events are used by the profile manager when
      it has to provide the trust that has an user that another does a certain action.

    contact:
      name: Bruno Rosell i Gui (UDT-IA, IIIA-CSIC)
      email: rosell@iiia.csic.es
    license:
      name: MIT
      url: https://opensource.org/licenses/MIT
  servers:
    - url: https://wenet.u-hopper.com/prod/profile_manager
      description: WeNet production server
    - url: https://wenet.u-hopper.com/dev/profile_manager
      description: WeNet development server server
    - url: http://ardid.iiia.csic.es/wenet/profile-manager/0.3.0/
      description: IIIA development server
