version: "3"
services:
  database:
    image: mongo:4.2.3
    container_name: wenet_profile_manager_database
    restart: always
    ports:
      - ${DB_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${DB_NAME:-wenetProfileManagerDB}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - wenet_profile_manager_data:/data/db
  api:
    build:
      context: .
      args:
        API_PORT: 8080
        DB_HOST: database
        DB_PORT: ${DB_PORT:-27017}
        DB_NAME: ${DB_NAME:-wenetProfileManagerDB}
        DB_USER_NAME: ${DB_USER_NAME:-wenetProfileManager}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD:-password}
    image: "wenet/profile-manager"
    ports:
      - "${API_PORT:-80}:8080"
    depends_on:
     - database
    environment:
      API_PORT: 8080
      DB_HOST: database
      DB_PORT: ${DB_PORT:-27017}
      DB_NAME: ${DB_NAME:-wenetProfileManagerDB}
      DB_USER_NAME: ${DB_USER_NAME:-wenetProfileManager}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD:-password}
volumes:
  wenet_profile_manager_data:
