version: "3"
services:
  wenet_profile_manager_database:
    image: mongo:4.2.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: wenetProfileManagerDB
    volumes:
      - ./initialize-wenetProfileManagerDB.js:/docker-entrypoint-initdb.d/init-mongo.js
      - wenet_profile_manager_data:/data/db
    networks:
      wenet_network:

  wenet_profile_manager_api:
    image: wenet/profile-manager:latest
    restart: always
    depends_on:
      - wenet_profile_manager_database
    environment:
      DB_HOST: wenet_profile_manager_database
      WAIT_HOSTS: wenet_profile_manager_database:27017
      WENET_INTERACTION_PROTOCOL_ENGINE_API_HOST: "https://wenet.u-hopper.com"
      WENET_INTERACTION_PROTOCOL_ENGINE_API_PORT: 80
      WENET_INTERACTION_PROTOCOL_ENGINE_API_PATH: "interaction_protocol_engine"
      WENET_TASK_MANAGER_API_HOST: "https://wenet.u-hopper.com"
      WENET_TASK_MANAGER_API_PORT: 80
      WENET_TASK_MANAGER_API_PATH: "task_manager"
    networks:
      wenet_network:
    ports:
      - ${PROFILE_MANAGER_API_PORT:-8081}:8080

volumes:
    wenet_profile_manager_data:

networks:
    wenet_network:
